apiVersion: v1
kind: Service
metadata:
  name: demo-app-2
  namespace: example-2
spec:
  ports:
  - port: 3456
    protocol: TCP
    targetPort: 3456
  selector: 
    app: demo-app-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app-2
  name: demo-app-2
  namespace: example-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-2
  template:
    metadata:
      labels:
        app: demo-app-2
    spec:
      volumes:
        - name: otelcol-demo3-configmap
          configMap:
            name: otelcol-demo3-configmap
            items:
              - key: relay
                path: relay.yaml
      containers:
      - env:
        - name: DEMO_APP_NAME
          value: example2-d3-otel-demo-2
        - name: DEMO_APP_PORT
          value: "3457"
        - name: DEMO_APP_TARGET_HOST
          value: http://demo-app-1.example-2
        - name: DEMO_APP_TARGET_PORT
          value: "3456"
        - name: OTEL_SERVICE_NAME
          value: example2-d3-otel-demo-2
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://127.0.0.1:4318
        - name: OTEL_NODE_RESOURCE_DETECTORS
          value: env,host,os
        - name: NODE_OPTIONS
          value: --require @opentelemetry/auto-instrumentations-node/register
        image: ghcr.io/whizus-labs/workshop-otel-introduction/otel-demo-app:latest
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 3456
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      - name: sidecar
        args:
          - --config=/conf/relay.yaml
        image: "otel/opentelemetry-collector-k8s:0.106.1"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
          - mountPath: /conf
            name: otelcol-demo3-configmap
