config: 
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  processors:
    batch: {}

  exporters:
    debug: {}
    otlp/jaeger:
      endpoint: jaeger-all-in-one-collector.monitoring:4317
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers:
        - otlp
        processors:
        - batch
        exporters:
        - otlp/jaeger
          