apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  mode: deployment # This configuration is omittable.
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}

    exporters:
      debug: {}
      otlp/jaeger:
        endpoint: http://jaeger-all-in-one-collector.monitoring:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers:
          - otlp
          processors:
          - batch
          exporters:
          - otlp/jaeger
          

