apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: sidecar
spec:
  exporter:
    endpoint: http://127.0.0.1:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
 