---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  namespace: example-1
  labels:
    app.kubernetes.io/name: otel-agent
    app.kubernetes.io/component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    processors:
      batch:
    exporters:
      otlp:
        endpoint: "jaeger-all-in-one-collector.monitoring:4317"
        tls:
          insecure: true
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp
