---
apiVersion: v1
kind: Service
metadata:
  name: otel-agent
  namespace: example-1
  labels:
    app.kubernetes.io/name: otel-agent
    app.kubernetes.io/component: otel-agent-service
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: metrics
    port: 8888
  selector:
    app.kubernetes.io/name: otel-agent
    app.kubernetes.io/component: otel-agent-pod
