---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: example-1
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/component: demo-app-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
      app.kubernetes.io/component: demo-app-pod
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-app
        app.kubernetes.io/component: demo-app-pod
    spec:
      containers:
      - image: ghcr.io/whizus-labs/workshop-otel-introduction/otel-demo-app:latest
        imagePullPolicy: IfNotPresent
        name: app
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: DEMO_APP_NAME
          value: example-1-demo
        - name: DEMO_APP_PORT
          value: "8080"
        - name: DEMO_APP_TARGET_HOST
          value: "http://demo-app2.example-1"
        - name: DEMO_APP_TARGET_PORT
          value: "8080"
        - name: OTEL_SERVICE_NAME
          value: "example-1-demo"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-agent.example-1:4318"
        - name: OTEL_NODE_RESOURCE_DETECTORS
          value: "env,host,os"
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app2
  namespace: example-1
  labels:
    app.kubernetes.io/name: demo-app2
    app.kubernetes.io/component: demo-app2-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app2
      app.kubernetes.io/component: demo-app2-pod
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-app2
        app.kubernetes.io/component: demo-app2-pod
    spec:
      containers:
      - image: ghcr.io/whizus-labs/workshop-otel-introduction/otel-demo-app:latest
        imagePullPolicy: IfNotPresent
        name: app
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: DEMO_APP_NAME
          value: demo2
        - name: DEMO_APP_PORT
          value: "8080"
        - name: DEMO_APP_TARGET_HOST
          value: "http://demo-app.example-1"
        - name: DEMO_APP_TARGET_PORT
          value: "8080"
        - name: OTEL_SERVICE_NAME
          value: "demo2"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-agent.example-1:4318"
        - name: OTEL_NODE_RESOURCE_DETECTORS
          value: "env,host,os"
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
